- name: Prepare for cleanup
  hosts: localhost
  gather_facts: false
  tags:
    - always

  tasks:
    - name: Try to log in as openshift admin
      command: oc login -u system:admin
      register: oc_login
      changed_when: oc_login.rc == 0
      # If login failed, cluster is probably down - that means steps which use
      # `oc` must be skipped, but otherwise, cleanup can proceed as usual
      ignore_errors: true


- name: Delete koji
  hosts: localhost
  gather_facts: false
  tags:
    - koji
    # One tag to rule them all
    - everything

  tasks:
    - name: Delete koji project from openshift
      command: oc delete project/"{{ koji_project }}"
      register: delete_koji_project
      changed_when: delete_koji_project.rc == 0
      failed_when: delete_koji_project.rc != 0 and
                   'cannot delete resource "projects"' not in delete_koji_project.stderr
      when: not oc_login.failed


- name: Delete docker registry
  hosts: localhost
  gather_facts: false
  tags:
    - registry
    - everything

  tasks:
    - name: Delete registry project from openshift
      command: oc delete project/"{{ registry_project }}"
      register: delete_registry_project
      changed_when: delete_registry_project.rc == 0
      failed_when: delete_registry_project.rc != 0 and
                   'cannot delete resource "projects"' not in delete_registry_project.stderr
      when: not oc_login.failed
      ignore_errors: true

- name: Delete OSBS orchestrator and worker projects
  hosts: localhost
  gather_facts: false
  tags:
    - osbs
    - everything

  tasks:
    - name: Delete orchestrator and worker projects from openshift
      command: oc delete project/"{{ item }}"
      register: delete_osbs_project
      changed_when: delete_osbs_project.rc == 0
      failed_when: delete_osbs_project.rc != 0 and
                   'cannot delete resource "projects"' not in delete_osbs_project.stderr
      loop:
        - "{{ orchestrator_project }}"
        - "{{ worker_project }}"
      when: not oc_login.failed
      ignore_errors: true


- name: Delete remaining OSBS-Box data
  hosts: localhost
  gather_facts: false
  tags:
    - never
    - everything

  tasks:
    - name: Delete certificate directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ koji_certs_dir }}"
        - "{{ registry_certs_dir }}"
        - "{{ certificates_dir }}"
      tags:
        - certificates

    - name: Delete openshift files directory
      file:
        path: "{{ openshift_files }}"
        state: absent
      tags:
        - openshift_files

    - name: Delete OSBS-Box data directory
      # At this point, it should only contain empty directories (if anything)
      file:
        path: "{{ osbs_box_data_dir }}"
        state: absent
