kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: koji-volumes
  description: >
    Persistent volumes for koji data. There is one volume for koji-db data
    and one for the /mnt/koji/ file hierarchy. They are HostPath volumes.

    The reclaim policy for these volumes is Retain, meaning the data is never
    removed (not by openshift, anyway).

    The persistent volume claims that bind to these PVs are also defined here.

parameters:
  - name: OCP_USER
    description: OCP username to prefix PVCs with
    required: true

labels:
  volume: koji-volume

objects:
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: ${OCP_USER}-koji-files
    spec:
      volumeName: koji-files
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi

  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: ${OCP_USER}-koji-db-data
    spec:
      volumeName: koji-db-data
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
